/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_cpu' in SOPC Builder design 'nios2_system'
 * SOPC Builder design path: ../../QuartusII/nios2/nios2_system.sopcinfo
 *
 * Generated: Fri May 05 14:18:40 JST 2023
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00040820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 54000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x13
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 54000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x13
#define ALT_CPU_NAME "nios2_cpu"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00040820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 54000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x13
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x13
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_I2C
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x42000
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x42000
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x42000
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios2_system"


/*
 * fifo_rx_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_rx_in_csr altera_avalon_fifo
#define FIFO_RX_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_RX_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_RX_IN_CSR_BASE 0x47000
#define FIFO_RX_IN_CSR_BITS_PER_SYMBOL 8
#define FIFO_RX_IN_CSR_CHANNEL_WIDTH 0
#define FIFO_RX_IN_CSR_ERROR_WIDTH 0
#define FIFO_RX_IN_CSR_FIFO_DEPTH 16
#define FIFO_RX_IN_CSR_IRQ 1
#define FIFO_RX_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define FIFO_RX_IN_CSR_NAME "/dev/fifo_rx_in_csr"
#define FIFO_RX_IN_CSR_SINGLE_CLOCK_MODE 1
#define FIFO_RX_IN_CSR_SPAN 32
#define FIFO_RX_IN_CSR_SYMBOLS_PER_BEAT 4
#define FIFO_RX_IN_CSR_TYPE "altera_avalon_fifo"
#define FIFO_RX_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define FIFO_RX_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_RX_IN_CSR_USE_AVALONST_SINK 1
#define FIFO_RX_IN_CSR_USE_AVALONST_SOURCE 0
#define FIFO_RX_IN_CSR_USE_BACKPRESSURE 1
#define FIFO_RX_IN_CSR_USE_IRQ 1
#define FIFO_RX_IN_CSR_USE_PACKET 0
#define FIFO_RX_IN_CSR_USE_READ_CONTROL 0
#define FIFO_RX_IN_CSR_USE_REGISTER 0
#define FIFO_RX_IN_CSR_USE_WRITE_CONTROL 1


/*
 * fifo_rx_out configuration
 *
 */

#define ALT_MODULE_CLASS_fifo_rx_out altera_avalon_fifo
#define FIFO_RX_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define FIFO_RX_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define FIFO_RX_OUT_BASE 0x46000
#define FIFO_RX_OUT_BITS_PER_SYMBOL 8
#define FIFO_RX_OUT_CHANNEL_WIDTH 0
#define FIFO_RX_OUT_ERROR_WIDTH 0
#define FIFO_RX_OUT_FIFO_DEPTH 16
#define FIFO_RX_OUT_IRQ -1
#define FIFO_RX_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FIFO_RX_OUT_NAME "/dev/fifo_rx_out"
#define FIFO_RX_OUT_SINGLE_CLOCK_MODE 1
#define FIFO_RX_OUT_SPAN 8
#define FIFO_RX_OUT_SYMBOLS_PER_BEAT 4
#define FIFO_RX_OUT_TYPE "altera_avalon_fifo"
#define FIFO_RX_OUT_USE_AVALONMM_READ_SLAVE 1
#define FIFO_RX_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define FIFO_RX_OUT_USE_AVALONST_SINK 1
#define FIFO_RX_OUT_USE_AVALONST_SOURCE 0
#define FIFO_RX_OUT_USE_BACKPRESSURE 1
#define FIFO_RX_OUT_USE_IRQ 1
#define FIFO_RX_OUT_USE_PACKET 0
#define FIFO_RX_OUT_USE_READ_CONTROL 0
#define FIFO_RX_OUT_USE_REGISTER 0
#define FIFO_RX_OUT_USE_WRITE_CONTROL 1


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * i2c_0 configuration
 *
 */

#define ALT_MODULE_CLASS_i2c_0 altera_avalon_i2c
#define I2C_0_BASE 0x45000
#define I2C_0_FIFO_DEPTH 4
#define I2C_0_FREQ 54000000
#define I2C_0_IRQ 2
#define I2C_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define I2C_0_NAME "/dev/i2c_0"
#define I2C_0_SPAN 64
#define I2C_0_TYPE "altera_avalon_i2c"
#define I2C_0_USE_AV_ST 1


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x42000
#define JTAG_UART_IRQ 4
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * msgdma_tx_csr configuration
 *
 */

#define ALT_MODULE_CLASS_msgdma_tx_csr altera_msgdma
#define MSGDMA_TX_CSR_BASE 0x43000
#define MSGDMA_TX_CSR_BURST_ENABLE 0
#define MSGDMA_TX_CSR_BURST_WRAPPING_SUPPORT 0
#define MSGDMA_TX_CSR_CHANNEL_ENABLE 0
#define MSGDMA_TX_CSR_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_TX_CSR_CHANNEL_WIDTH 8
#define MSGDMA_TX_CSR_DATA_FIFO_DEPTH 32
#define MSGDMA_TX_CSR_DATA_WIDTH 16
#define MSGDMA_TX_CSR_DESCRIPTOR_FIFO_DEPTH 8
#define MSGDMA_TX_CSR_DMA_MODE 1
#define MSGDMA_TX_CSR_ENHANCED_FEATURES 0
#define MSGDMA_TX_CSR_ERROR_ENABLE 0
#define MSGDMA_TX_CSR_ERROR_ENABLE_DERIVED 0
#define MSGDMA_TX_CSR_ERROR_WIDTH 8
#define MSGDMA_TX_CSR_IRQ 3
#define MSGDMA_TX_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MSGDMA_TX_CSR_MAX_BURST_COUNT 2
#define MSGDMA_TX_CSR_MAX_BYTE 1024
#define MSGDMA_TX_CSR_MAX_STRIDE 1
#define MSGDMA_TX_CSR_NAME "/dev/msgdma_tx_csr"
#define MSGDMA_TX_CSR_PACKET_ENABLE 0
#define MSGDMA_TX_CSR_PACKET_ENABLE_DERIVED 0
#define MSGDMA_TX_CSR_PREFETCHER_ENABLE 0
#define MSGDMA_TX_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_TX_CSR_RESPONSE_PORT 2
#define MSGDMA_TX_CSR_SPAN 32
#define MSGDMA_TX_CSR_STRIDE_ENABLE 0
#define MSGDMA_TX_CSR_STRIDE_ENABLE_DERIVED 0
#define MSGDMA_TX_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define MSGDMA_TX_CSR_TYPE "altera_msgdma"


/*
 * msgdma_tx_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_msgdma_tx_descriptor_slave altera_msgdma
#define MSGDMA_TX_DESCRIPTOR_SLAVE_BASE 0x44000
#define MSGDMA_TX_DESCRIPTOR_SLAVE_BURST_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define MSGDMA_TX_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 32
#define MSGDMA_TX_DESCRIPTOR_SLAVE_DATA_WIDTH 16
#define MSGDMA_TX_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 8
#define MSGDMA_TX_DESCRIPTOR_SLAVE_DMA_MODE 1
#define MSGDMA_TX_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define MSGDMA_TX_DESCRIPTOR_SLAVE_IRQ -1
#define MSGDMA_TX_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MSGDMA_TX_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 2
#define MSGDMA_TX_DESCRIPTOR_SLAVE_MAX_BYTE 1024
#define MSGDMA_TX_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define MSGDMA_TX_DESCRIPTOR_SLAVE_NAME "/dev/msgdma_tx_descriptor_slave"
#define MSGDMA_TX_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define MSGDMA_TX_DESCRIPTOR_SLAVE_SPAN 16
#define MSGDMA_TX_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define MSGDMA_TX_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define MSGDMA_TX_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * onchip_NVM_ROM configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_NVM_ROM altera_avalon_onchip_memory2
#define ONCHIP_NVM_ROM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_NVM_ROM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_NVM_ROM_BASE 0x60000
#define ONCHIP_NVM_ROM_CONTENTS_INFO ""
#define ONCHIP_NVM_ROM_DUAL_PORT 0
#define ONCHIP_NVM_ROM_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_NVM_ROM_INIT_CONTENTS_FILE "X68KeplerX-BusController"
#define ONCHIP_NVM_ROM_INIT_MEM_CONTENT 1
#define ONCHIP_NVM_ROM_INSTANCE_ID "NONE"
#define ONCHIP_NVM_ROM_IRQ -1
#define ONCHIP_NVM_ROM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_NVM_ROM_NAME "/dev/onchip_NVM_ROM"
#define ONCHIP_NVM_ROM_NON_DEFAULT_INIT_FILE_ENABLED 1
#define ONCHIP_NVM_ROM_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_NVM_ROM_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_NVM_ROM_SINGLE_CLOCK_OP 0
#define ONCHIP_NVM_ROM_SIZE_MULTIPLE 1
#define ONCHIP_NVM_ROM_SIZE_VALUE 256
#define ONCHIP_NVM_ROM_SPAN 256
#define ONCHIP_NVM_ROM_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_NVM_ROM_WRITABLE 0


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x20000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 1
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "nios2_system_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 1
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 40960
#define ONCHIP_MEMORY_SPAN 40960
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * pio_dipsw configuration
 *
 */

#define ALT_MODULE_CLASS_pio_dipsw altera_avalon_pio
#define PIO_DIPSW_BASE 0x41000
#define PIO_DIPSW_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_DIPSW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_DIPSW_CAPTURE 1
#define PIO_DIPSW_DATA_WIDTH 4
#define PIO_DIPSW_DO_TEST_BENCH_WIRING 0
#define PIO_DIPSW_DRIVEN_SIM_VALUE 0
#define PIO_DIPSW_EDGE_TYPE "RISING"
#define PIO_DIPSW_FREQ 54000000
#define PIO_DIPSW_HAS_IN 1
#define PIO_DIPSW_HAS_OUT 0
#define PIO_DIPSW_HAS_TRI 0
#define PIO_DIPSW_IRQ -1
#define PIO_DIPSW_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_DIPSW_IRQ_TYPE "NONE"
#define PIO_DIPSW_NAME "/dev/pio_dipsw"
#define PIO_DIPSW_RESET_VALUE 0
#define PIO_DIPSW_SPAN 16
#define PIO_DIPSW_TYPE "altera_avalon_pio"


/*
 * pio_led configuration
 *
 */

#define ALT_MODULE_CLASS_pio_led altera_avalon_pio
#define PIO_LED_BASE 0x41010
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 8
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE "NONE"
#define PIO_LED_FREQ 54000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ -1
#define PIO_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_IRQ_TYPE "NONE"
#define PIO_LED_NAME "/dev/pio_led"
#define PIO_LED_RESET_VALUE 0
#define PIO_LED_SPAN 16
#define PIO_LED_TYPE "altera_avalon_pio"


/*
 * pio_scroll_y configuration
 *
 */

#define ALT_MODULE_CLASS_pio_scroll_y altera_avalon_pio
#define PIO_SCROLL_Y_BASE 0x41020
#define PIO_SCROLL_Y_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_SCROLL_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_SCROLL_Y_CAPTURE 0
#define PIO_SCROLL_Y_DATA_WIDTH 8
#define PIO_SCROLL_Y_DO_TEST_BENCH_WIRING 0
#define PIO_SCROLL_Y_DRIVEN_SIM_VALUE 0
#define PIO_SCROLL_Y_EDGE_TYPE "NONE"
#define PIO_SCROLL_Y_FREQ 54000000
#define PIO_SCROLL_Y_HAS_IN 0
#define PIO_SCROLL_Y_HAS_OUT 1
#define PIO_SCROLL_Y_HAS_TRI 0
#define PIO_SCROLL_Y_IRQ -1
#define PIO_SCROLL_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_SCROLL_Y_IRQ_TYPE "NONE"
#define PIO_SCROLL_Y_NAME "/dev/pio_scroll_y"
#define PIO_SCROLL_Y_RESET_VALUE 0
#define PIO_SCROLL_Y_SPAN 16
#define PIO_SCROLL_Y_TYPE "altera_avalon_pio"


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x4f000
#define SYSID_QSYS_0_ID 0
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1683263771
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"


/*
 * textram configuration
 *
 */

#define ALT_MODULE_CLASS_textram altera_avalon_onchip_memory2
#define TEXTRAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TEXTRAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TEXTRAM_BASE 0x50000
#define TEXTRAM_CONTENTS_INFO ""
#define TEXTRAM_DUAL_PORT 1
#define TEXTRAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define TEXTRAM_INIT_CONTENTS_FILE "nios2_system_textram"
#define TEXTRAM_INIT_MEM_CONTENT 1
#define TEXTRAM_INSTANCE_ID "NONE"
#define TEXTRAM_IRQ -1
#define TEXTRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TEXTRAM_NAME "/dev/textram"
#define TEXTRAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define TEXTRAM_RAM_BLOCK_TYPE "AUTO"
#define TEXTRAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define TEXTRAM_SINGLE_CLOCK_OP 1
#define TEXTRAM_SIZE_MULTIPLE 1
#define TEXTRAM_SIZE_VALUE 8192
#define TEXTRAM_SPAN 8192
#define TEXTRAM_TYPE "altera_avalon_onchip_memory2"
#define TEXTRAM_WRITABLE 1

#endif /* __SYSTEM_H_ */
